protected/models/Project.php
<?php

/*class Project{
	
	
		$db = connectMongo();
		$collection = $db->projects;
		$project = $collection->findOne(array('_id'=>new MongoId($id)));
		//$topic = $c->findOne(array('_id'=>new MongoId($id)));
		
	}
*/

protected/controllers/ProjectController.php
<?php
 
class ProjectController extends Controller
{
	

	public function connectMongo($mydb,$c)
	{	
		try {
		$mongo = new MongoClient();
		$db = $mongo->selectDB($mydb);
		$collection = $db->c;
		return $collection;
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}
	}

	public function actionIndex()
	{	
		try {
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$collection = $db->projects; // select collection 
		$p = $collection->find(); //list all the projects in the DB 
		}
		catch (MongoException $e)
		{
			$e->getMessage();
		}
		$this->render('index',array('projects' => $p));
	}

	
	public function actionRead()  // read operation is working. 
	{
		try 
		{
		$mongo = new MongoClient();
		$db = $mongo->selectDB("mydb");
		$collection = $db->projects;
		$mongo = new MongoClient();
		$db = $mongo->selectDB("mydb");
		$collection = $db->projects;
		//$prj = array('name'=>'name');
		$q = $_GET['name'];
		//echo $q;
		$query = array( "name" => $q); 
		$cursor = $collection->findOne($query);
		// get the list of team members. 
		$u = $db->users;
		
		//echo $cursor['members'][0]['userid'];
		$users = $u->find();
		}
		catch (MongoException $e)
		{
			$e->getMessage();
		}
		$this->render('read',array('project' => $cursor, 'users'=>$users));
	}

	public function actionDelete() // not yet done.
	{
		$this->render('delete');
	}

	public function actionNew()  //creates a new record 
	{
		//$collection = $this->connectMongo("mydb","users");
		try
		{ 
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$collection = $db->users; // select collection 

		$cursor = $collection->find(); 
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}
		$this->render('create',array('users' => $cursor));
	}
	public function actionCreate() // writes new record to db. 
	{ 
		$data  = $_POST;
		try { 
		$mongo = new MongoClient();
		$db = $mongo->mydb;
		$collection = $db->projects;
		//$project = $data;
		$project['name'] = $data['name'];
		$project['desc'] = $data['desc'];
		$project['start_date'] = "1-6-2013";
		$project['status'] = 1;
		/*$i=0;
		/*$c = $db->users;
		$q = $data['uname1'];
		$query = array( "username" => $q); 
		$uname = $c->findOne($query);*/
		//echo "userid : ".$uname['userid'];
		//echo $data['role1']['role'];
		/*$project['team'][$i]['userid']=$data['uname1']; // the team is nested array. 
		$project['team'][$i]['role']= $data['role1'];
		$i++;
		$c = $db->users;
		$q = $data['uname2'];
		$query = array( "username" => $q);
		$uname = $c->findOne($query);
		$project['team'][$i]['userid']= $data['uname1'];
		$project['team'][$i]['role']= $data['role2'];*/

		$collection->insert($project);
		$p = $collection->find();
		}
		catch (MongoException $e)
		{
			 $e->getMessage();
		}

	 $this->render('index',array('projects'=> $p));	
	}

	public function actionNewMember()
	{	
		//$p = $this->connectMongo("mydb","projects");
		try { 
		$mongo = new MongoClient();
		$db = $mongo->mydb;
		$p = $db->projects;
		$projects = $p->find();
		$mongo = new MongoClient();
		$db = $mongo->mydb;
		$u = $db->users;
		//$u = connectMongo("mydb","users");
		$users = $u->find();
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}

		$this->render('new_member',array('projects'=>$projects,'users'=>$users));
	}
	public function actionRemoveUser()
	{
		try { 
		$mongo = new MongoClient();
		$db = $mongo->selectDB('mydb');
		$p = $db->projects;
		$pid = $_GET['pid'];
		$uid = $_GET['uid'];
		$p->update(array("_id"=> new MongoId($pid)),array('$pull'=>array('members'=>array("userid"=>$uid))));
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}
		$this->actionIndex();


	}

	public function actionAddMember()
	{	
		try { 
		$mongo = new MongoClient();
		$db = $mongo->mydb;
		$p = $db->projects;
		$project = $p->findOne(array("_id"=> new MongoId($_POST['project'])));
		//$p->update(array("_id"=> new MongoId($_POST['project'])),array('$push'=>array("userid"=>$_POST['user'],"role"=>$_POST['role'])));	
		/*foreach ($project['members'] as $u) {
			# code...
			if($u['userid'] == $_POST['user'])
		    {		
			echo "<h3> Cannot add user! this user is already added.</h3>";
			exit();
			}
		}*/
		$tm = $p->findOne(array("_id"=> new MongoId($_POST['project']),"members.userid"=>$_POST['user']));
		if (isset($tm))
		{
			// I want to flash a message here 
			echo "<h3> Cannot add user! this user is already added.</h3>";
			exit();
		}
		else
			$p->update(array("_id"=> new MongoId($_POST['project'])),array('$push'=>array('members'=>array("userid"=>$_POST['user'],"role"=>$_POST['role']))));
	}
		catch(MongoException $e)
		{
			$e->getMessage();
		}
		$this->actionIndex();
	}

	public function actionChangeRole()
	{
		try { 
		$mongo = new MongoClient();
		$db = $mongo->selectDB("mydb");
		$p= $db->projects;

		$q = $_GET['uid'];
		//echo $_GET['pid'];
		//$q=array(("_id"= new MongoId($_GET['pid'])));
		$project =$p->findOne(array("_id"=> new MongoId($_GET['pid'])));
		
		

		//$query = array( "userid" => $q); 
		//$r = $p->findOne("members"=>$query);*/
		//var_dump($_GET) ;
	 	//$pid = $CURRENT_PID;
		//$p->update(array("_id"=>new MongoId($_GET['uid'])),array('$set'));
		}

		catch (MongoException $e)
		{
			$e->getMessage();
		}
		$this->render('change_role',array('uid'=>$_GET['uid'],'project'=>$project));
			
	}
	public function actionUpdateRole()
	{	
		try { 
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$p = $db->projects; // select collection 
		echo $_POST['role'];
		$project = $p->findOne(array("_id"=> new MongoId($_POST['pid'])));
		//	echo $project['_id'];
		$roleupdate = array("members.$.role"=>$_POST['role']);
		$p->update(array("_id"=>new MongoId($_POST['pid']),"members.userid"=>$_POST['uid']),array('$set'=>$roleupdate));
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}

		$this->actionIndex();
		
	}

	public function actionCreateIssue()
	{
		try { 
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$collection = $db->users; // select collection 
		$u = $collection->find(); //list all users		
		}
		catch (MongoException $e )
		{
			$e->getMessage();
		}
		$pid = $_GET['pid']; // get the project Id and pass to view.
		$this->render('create_issue',array('pid'=>$pid,'user'=>$u));

	}

	

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/views/project/_form.php
<?php
/* @var $this ProjectController */
/* @var $model Project */
/* @var $form CActiveForm */
?>

<div class="form">
<form action="<?php echo $this->createUrl('project/create')?>" method="POST">
	<label> Project Name</label>
	<input type="text" name ="name" placeholder = "Project Name"><br />
	<textarea name = "desc" placeholder = "Description" cols=40 rows=6></textarea>  <br />
	<!-- <h6> Team Members </h6>
	<label> User</label>
	<select name="uname1">
		  <?php foreach ($users as $u) {
		  	echo "<option value=".$u['_id'].">".$u['username']."</option>"; // display user's list 
		  } 

		  ?>

	</select> <br />
	<label> Role</label>
	<select name ="role1">
		<option value = "Developer"> Developer </option>
		<option value = "Tester"> Tester </option>
		<option value = "sysOp"> sysOp </option>
	</select>
	<?php //$_POST['role1']= ?>
	<br />
	<label> User</label>
	<select name="uname2">
		  <?php foreach ($users as $u) {
		  	echo "<option value=".$u['_id'].">".$u['username']."</option>"; // display user's list
		  } 
		  	// $_POST['uid2']=$u['_id'];
		  ?>

	</select> <br />
	<label> Role</label>
	<select name = "role2">
		<option value = "Developer"> Developer </option>
		<option value = "Tester"> Tester </option>
		<option value = "sysOp"> sysOp </option>
	</select>
	<br />
	 -->
	<button type="submit"> Create Project </button> 
</form>

</div><!-- form -->

protected/views/project/change_role.php
<h3> Change the Role of user in Project </h3>
<div class="form">
<form action="<?php echo $this->createUrl('project/updateRole')?>" method="POST">
<?php 
	$u = new User;
	$user = $u->getUser($uid);
	$_POST['uid'] = $uid;
	echo "<h5>". $user['fname'] ." ".$user['lname']. "</h5>";
	//echo $_POST['uid'];
	$_POST['pid'] = $project['_id'];
	//echo $_POST['pid'];

 ?>
 <label>Project</label>
 <?php echo "<h5>". $project['name'] . "</h5>";?>
 <input type="hidden" name = "pid" value="<?php echo $project['_id'] ?>"
 
 <br />
 <label>User</label>
 <?php echo "<h5>". $user['fname'] ." ".$user['lname']. "</h5>";?>
 <input type="hidden" name="uid" value="<?php echo $uid ?>"/>
 <!--<select name="uid">
 	<option value="<?php echo $uid ?>"><?php echo "<h5>". $user['fname'] ." ".$user['lname']. "</h5>";?> </option>
 	</select>-->

 
 	<?php foreach ($project['members'] as $ur)
 	{
			if($ur['userid'] == $uid){
				$cr= $ur['role'];
				break;
			}
	}
	//echo $cr;
     ?>
 <label> Role</label>
	<select name ="role">

		<option <?php if($cr == "Developer") echo "selected" ?> value = "Developer"> Developer </option>
		<option <?php if($cr == "Tester") echo "selected" ?> value = "Tester"> Tester </option>
		<option <?php if($cr == "sysOp") echo "selected" ?> value = "sysOp"> sysOp </option>
	</select>
	<br />
	<button type="submit"> Update Role </button> 
</form>

</div><!-- form 9739608800-->

protected/views/project/create.php
<?php
/* @var $this ProjectController */
/* @var $model Project */

$this->breadcrumbs=array(
	'Projects'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Project', 'url'=>array('index')),
	array('label'=>'Manage Project', 'url'=>array('admin')),
);
?>

<h1>Create Project</h1>

<?php echo $this->renderPartial('_form',array('users'=>$users)); ?>

protected/views/project/index.php
<?php
/* @var $this ProjectController */

$this->breadcrumbs=array(
	'Project',
);
?>
<?php foreach ($projects as $prj)
	{	 
		 echo CHtml::link ("<h3>". $prj['name']. "</h3>",array("project/read&name=".$prj['name'])) ; 
	 } 
?>

protected/views/project/new_member.php
<div class="form">
<form action="<?php echo $this->createUrl('project/addMember')?>" method="POST">
<label> Project</label>
	<select name="project">
	<?php foreach ($projects as $p) {
		  	echo "<option value=".$p['_id'].">".$p['name']."</option>"; // display projects list 
		  } 

		  ?>
	</select>
	<br />
	<label> Team Member</label>
	<select name="user">
	<?php foreach ($users as $u) {
		  	echo "<option value=".$u['_id'].">".$u['fname']."</option>"; // display projects list 
		  } 

		  ?>
	</select>
	<br />
	<label> Role</label>
	<select name ="role">
		<option value = "Developer"> Developer </option>
		<option value = "Tester"> Tester </option>
		<option value = "sysOp"> sysOp </option>
	</select>
	<br />

<button type="submit"> Add Team Member </button> 
</form>

</div><!-- form -->

protected/views/project/read.php
<?php
echo "<h4 style='float:right'>";
echo CHtml::link("Create issue",array('issue/createIssue&pid='.$project['_id']));
echo "</h4>";
echo "<h3>Name: ". $project['name']. "</h3><br />";
echo "<h6>Desc: ". $project['desc']. "</h6> <br />";
//$id= $project['members'][0]['userid'];
//$user= new User;
//echo $id;
//$u = $users->getUser($id);
//echo "$u";
//$_GET['pid'] = $project['_id'];
//echo $_GET['pid'];
?>

<div class = "form">
<form action="<?php echo $this->createUrl('project/ChangeRole') ?>" method ="GET">
 <table>
<tr>
<th> Member </th>
<th> Role </th>
</tr>
<?php
$users = new User;
foreach($project['members'] as $user)
	{	
			$u = $users->getUser($user['userid']);
		
			echo "<tr><td>".$u['username']. " </td>  "."<td>".$user['role']. "</td> <td>".CHtml::link("Edit Role",array('project/changeRole&uid='.$user['userid']."&pid=".$project['_id']))."</td><td>".CHtml::link("Remove User",array('project/removeUser&uid='.$user['userid']."&pid=".$project['_id']))."</td></tr>" ;
			
	}
//echo "<h6>". $project['members'][0]['userid']. "</h6> <br />";
/*echo "User Name: ". $user. " <br />";
echo "User Role: ". $project['members'][]['role'];*/

echo "</table><h6>". $project['status']. "</h6> <br />";

?>
</form>
</div>

protected/views/project/update_role.php
<?php
/* @var $this ProjectController */

$this->breadcrumbs=array(
	'Project',
);
?>
<?php foreach ($projects as $prj)
	{	 
		 echo CHtml::link ("<h3>". $prj['name']. "</h3>",array("project/changeRole&name=".$prj['name'])) ; 
	 } 
?>