protected/models/User.php
<?php

class User
{
	public function getUser($id)
	{
		try {
		$mongo = new MongoClient();
		$db = $mongo->selectDB('mydb');
		$collection = $db->users;
		$q = array('_id'=> new MongoId($id));
		$user = $collection->findOne($q);
		return $user;
		
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}
	}
}

protected/controllers/UserController.php
<?php 

class UserController extends Controller
{
	public function actionIndex()
	{	
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$collection = $db->users; // select collection 
		$u = $collection->find(); //list all users
		$this->render('index',array('users' => $u));
	}

	public function actionNew()  
	{

		$this->render('create');
	}

	public function actionCreate()
	{
		 try {
		$mongo = new MongoClient();
		$db = $mongo->selectDB("mydb");
		$collection = $db->users;
		$data = $_POST;
		$user['username'] = $data['username'];
		$user['fname'] = $data['fname'];
		$user['lname'] = $data['lname'];
		$user['email'] = $data['email'];
		$user['phone'] = $data['phone'];
		$collection->insert($user);
		}
		catch (MongoException $e)
		{
		  $e->getMessage();
		}
		$u = $collection->find();
		$this->render('index',array('users'=> $u));	
	}

}

protected/views/user/_form.php
<?php
/* @var $this ProjectController */
/* @var $model Project */
/* @var $form CActiveForm */
?>

<div class="form">
<h5> Enter User Details </h5>
<form action="<?php echo $this->createUrl('user/create')?>" method="POST">
	<input type="text" name ="username" placeholder = "User Name"><br />
	<input type="text" name ="fname" placeholder = "First Name"> <br />
	<input type="text" name ="lname" placeholder = "Last Name"> <br />
	<input type="text" name ="email" placeholder = "email"> <br />
	<input type="text" name ="phone" placeholder = "Phone"> <br />
	<button type="submit"> Add user </button> 
</form>

protected/views/user/create.php
<?php
/* @var $this ProjectController */
/* @var $model Project */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Create Project</h1>

<?php echo $this->renderPartial('_form'); ?>

protected/views/user/index.php
<?php
/* @var $this ProjectController */

$this->breadcrumbs=array(
	'User',
);
?>
<?php foreach ($users as $u)
	{	 
		 echo CHtml::link ("<h3>". $u['username']. "</h3>",array("user/read&email=".$u['email'])) ; 
	 } 
?>