protected/controllers/IssueController.php
<?php

class IssueController extends Controller
{
	public function actionIndex()
	{	
		try { 
		$mongo = new MongoClient();
		$db  = $mongo->selectDB('mydb');
		$c = $db->issues;
		$iss = $c->find();
		}
		catch(MongoException $e )
		{
			$e->getMessage();
		}
		$this->render('index',array('issues'=>$iss));
	}

	public function actionRead()
	{	
		try { 
		$mongo = new MongoClient();
		$db = $mongo->selectDB('mydb');
		$c = $db->issues;
		$id = $_GET['id'];
		$iss = $c->findOne(array("_id"=> new MongoId($id)));
		}
		catch (MongoException $e)
		{
			$e->getMessage();
		}

		$this->render('read',array('issue'=>$iss));
	}

	public function actionCreateIssue()
	{
		try { 
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$collection = $db->projects; // select collection 
		$pid = $_GET['pid']; // get the project Id.
		$project = $collection->findOne(array("_id"=>new MongoId($pid)));
		}
		catch (MongoException $e)
		{
			$e->getMessage();
		}
		$this->render('create_issue',array('project'=>$project,));

	}
	public function actionCreate()
	{
		try { 
		$mongo = new MongoClient(); // connect mongo 
		$db = $mongo->selectDB("mydb"); //select a db 
		$issue = $db->issues;
		$data['issue'] = $_POST['issue'];
		$data['desc'] = $_POST['desc'];
		$data['type'] = $_POST['type'];

		$data2['status'] = $_POST['status'];
		$data2['userid'] = $_POST['user'];
		$curdate = date("d/m/Y") ;
		$data2['create_date'] = new mongoDate(strtotime($curdate));
		$data['status'] = array();
		$data['status'][] = $data2;
		$issue->insert($data);
		}
		catch (MongoException $e)
		{
			$e->getMessage();
		}
		$this->actionIndex();
	}

	public function actionChangeIssue()
	{
		$id = $_GET['id'];
		try { 
		$mongo = new MongoClient();
		$db = $mongo->mydb;
		$c = $db->issues;
		$iss = $c->findOne(array("_id"=> new MongoId($id)));
		}
		catch(MongoException $e)
		{
			$e->getMessage();
		}
		$this->render('changeIssue',array('issue'=>$iss));

	}

	public function actionUpdateIssue()
	{
		try { 
		$mongo = new MongoClient();
		$db = $mongo->mydb;
		$c = $db->issues;
		$id = $_POST['id'];
		$data2['status'] = $_POST['status'];
		$data2['userid'] = $_POST['user'];
		$curdate = date("d/m/Y") ;
		$data2['create_date'] = new mongoDate(strtotime($curdate));
		$data['status'] = array();
		$data['status'] = $data2;
		$c->update(array("_id"=> new MongoId($id)),array('$push'=>$data));
		}
		catch (MongoException $e)
		{
			$e->getMessage();
		}
		$this->actionIndex();
	}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/views/issue/_form.php
<?php

?>

<div class="form">
<form action="<?php echo $this->createUrl('issue/create')?>" method="POST">
	
	<input type="text" name ="issue" placeholder = "Issue"><br />
	<textarea name = "desc" placeholder = "Description" cols=40 rows=6></textarea>  <br />
	<label>Type</label>
	<select name ="type">
		<option value = "Bug"> Bug</option>
		<option value = "Feature"> Feature </option>
		<option value = "Enhancement"> Enhancement </option>
	</select> <br />
	<label>Status</label>
	<select name="status">
		<option value ="Reported">Reported</option>
		<option value ="Started">Started</option>
		<option value ="Completed">Completed</option>
	</select> <br />
	<label>Users</label>
	<select name ="user">
	  <?php 
	  	$users = new User;
	  	foreach ($project['members'] as $user) {
	  			 $u = $users->getUser($user['userid']);
		  	echo "<option value=".$u['_id'].">".$u['username']."</option>"; // display user's list
		  } 
		  	
		  ?>
	</select>
	<br />
	
	 
	<button type="submit"> Create Issue </button> 
</form>

</div><!-- form -->

protected/views/issue/changeIssue.php
<div class="form">
<form action="<?php echo $this->createUrl('issue/updateIssue')?>" method="POST">
	<input type = "hidden" name="id" value="<?php echo $issue['_id']?>"/>
	<h6> Issue:  <?php echo $issue['issue'] ?> </h6> <br />
	<h6> Description:  <?php echo $issue['desc'] ?> <br /> </h6><br /><br />
	<h6> Type:  <?php echo $issue['type'] ?> </h6> <br /><br /><br />
	<label>Status</label>
	<select name="status">
		<option value ="Reported">Reported</option>
		<option value ="Started">Started</option>
		<option value ="Completed">Completed</option>
	</select> <br />
	<label>Users</label>
	<select name ="user">
	  <?php 
	  	$users = new User;
	  	foreach ($issue['status'] as $st) {
	  			 $u = $users->getUser($st['userid']);
		  	echo "<option value=".$u['_id'].">".$u['username']."</option>"; // display user's list
		  } 
		  	
		  ?>
	</select>
	<br />
	
	 
	<button type="submit"> Update Issue </button> 
</form>

</div><!-- form -->

protected/views/issue/create_issue.php
<?php 

$this->renderPartial('_form',array('project'=>$project));
?>

protected/views/issue/index.php
<?php
/* @var $this IssueController */

foreach ($issues as $iss)
	{	 
		 echo CHtml::link ("<h3>". $iss['issue']. "</h3>",array("issue/read&id=".$iss['_id'])) ; 
	 } 
?>

protected/views/issue/read.php
<?php
echo "<h4 style='float:right'>";
echo CHtml::link("Update issue",array('issue/ChangeIssue&id='.$issue['_id']));
echo "</h4>";
echo "<h3>Name: ". $issue['issue']. "</h3><br />";
echo "<h6>Desc: ". $issue['desc']. "</h6> <br />"; ?>
<table> <tr> <th> Status </th> <th> Date </th></tr><?php
foreach ($issue['status'] as $st ) {
	# code...
	echo "<tr><td>".$st['status'] ."</td><td>". date('Y-m-d',$st['create_date']->sec). "</td></tr>";
}
?></table>